sudo: false
language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
script:
    - ./gradlew clean build
notifications:
    email: false